### ISSUE TITLE
Still work?  

### ISSUE THREAD

**Issue by PAHelper2** [satanasov/scraper#1]
I was looking at your scrape_movie() method, and it seems like the page has changed and it normal works.  

I've been able to come up with some fixes for some of the queries in scape_movie, but my xpath stuff is pretty weak:

```
name = tree.xpath('(//span[contains(concat(" ", normalize-space(@data-type), " "), " shoot ")])[1]/@data-title')
plot = tree.xpath('(//meta[contains(concat(" ", normalize-space(@name), " "), " description ")])[1]/@content')
date = tree.xpath('(//div[@class="shoot-info"])[1]//p[1]/text()[1][1]')[0].strip().split("date: ")[1]
```

**Comment by PAHelper2** [comment]
It looks like kink.com has reworked their search layout recently.  I've had results brute forcing searches by paging through /latest/1 - /latest/X under a channel.

**Comment by Uatschitchun** [comment]
Sadly it's not working anymore ;)

**Comment by satanasov** [comment]
I started UNI and we have python ... so guess what am I going to show.

**Comment by satanasov** [comment]
It's back in working conditions :D
